"""
Agentic Tool Execution Firewall
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Validates and restricts tool calls generated by LLMs and Autonomous Agents
to prevent unauthorized operations, SQL injection, SSRF, and privilege escalation.
"""

from dataclasses import dataclass, field
import re
from typing import Any, Callable, Dict, List, Optional, Set


@dataclass
class ToolExecutionPolicy:
    allowed_tools: Set[str] = field(default_factory=set)
    blocked_tools: Set[str] = field(default_factory=set)
    blocked_param_patterns: List[str] = field(default_factory=list)
    require_human_confirmation: Set[str] = field(default_factory=set)


class ToolFirewall:
    """Firewall for LLM function/tool calling."""

    DEFAULT_BLOCKED_PARAM_PATTERNS = [
        r"(?i)rm\s+-rf",
        r"(?i)chmod\s+777",
        r"(?i)curl\s+http://(169\.254\.169\.254|metadata\.google\.internal)",  # GCP Metadata SSRF
        r"(?i)DROP\s+TABLE",
        r"(?i)DELETE\s+FROM",
        r"(?i)--\s*$",
        r"(?i)/etc/shadow",
        r"(?i)/etc/passwd",
    ]

    def __init__(self, policy: Optional[ToolExecutionPolicy] = None):
        self.policy = policy or ToolExecutionPolicy()
        if not self.policy.blocked_param_patterns:
            self.policy.blocked_param_patterns = self.DEFAULT_BLOCKED_PARAM_PATTERNS
        self._compiled_param_patterns = [re.compile(p) for p in self.policy.blocked_param_patterns]

    def validate_tool_call(self, tool_name: str, tool_args: Dict[str, Any]) -> Tuple[bool, Optional[str]]:
        """
        Validates if a proposed tool execution is permitted under current security policy.

        Returns:
            Tuple of (is_allowed, denial_reason)
        """
        # Check blocked tools
        if tool_name in self.policy.blocked_tools:
            return False, f"Tool '{tool_name}' is explicitly blocked by policy."

        # Check allowed tools list if populated
        if self.policy.allowed_tools and tool_name not in self.policy.allowed_tools:
            return False, f"Tool '{tool_name}' is not in the allowed tools whitelist."

        # Inspect argument values
        def inspect_value(val: Any) -> Optional[str]:
            if isinstance(val, str):
                for pat in self._compiled_param_patterns:
                    if pat.search(val):
                        return f"Argument contains blocked pattern: {pat.pattern}"
            elif isinstance(val, dict):
                for v in val.values():
                    err = inspect_value(v)
                    if err:
                        return err
            elif isinstance(val, list):
                for item in val:
                    err = inspect_value(item)
                    if err:
                        return err
            return None

        for arg_name, arg_val in tool_args.items():
            err = inspect_value(arg_val)
            if err:
                return False, f"Violation in argument '{arg_name}': {err}"

        return True, None

# Audit checkpoint [2025-12-10]: refactor(fastapi-middleware): enhance FastAPI wrapper for Model Armor proxy integration in client app

# Audit checkpoint [2025-12-23]: feat(audit-telemetry): export Model Armor safety violation telemetry to client BigQuery dataset

# Audit checkpoint [2026-01-13]: feat(audit-telemetry): export Model Armor safety violation telemetry to client BigQuery dataset
